### ISSUE TITLE
nixpkgs-patched for clevis out of date

### ISSUE THREAD

**Issue by Suya1671** [camillemndn/nixos-config#1]
rt. When building my system config (which depends on yours for zotero-dev), I get the following error:

```
       error: hash mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs/pull/257525.patch':
         specified: sha256:0mss1kdkjr1v41yigl43k1k3y18k4m3dabq6dn4w84zf406avyh0
         got:       sha256:17cxw0bbhdhnj9ychxvjin9h5dzip5sfjzl0plkp18w02wi0qcca
```

I traced it back to https://github.com/camillemndn/nixos-config/blob/1785268b2a2dcde69e6e00fdc6009fe96c0ef035/flake.nix#L119C1-L122 being out of date

**Comment by camillemndn** [comment]
> rt. When building my system config (which depends on yours for zotero-dev), I get the following error:
> 
> 
> 
> ```
> 
>        error: hash mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs/pull/257525.patch':
> 
>          specified: sha256:0mss1kdkjr1v41yigl43k1k3y18k4m3dabq6dn4w84zf406avyh0
> 
>          got:       sha256:17cxw0bbhdhnj9ychxvjin9h5dzip5sfjzl0plkp18w02wi0qcca
> 
> ```
> 
> 
> 
> I traced it back to https://github.com/camillemndn/nixos-config/blob/1785268b2a2dcde69e6e00fdc6009fe96c0ef035/flake.nix#L119C1-L122 being out of date

Hi, thank you, I think I ought to create a specific flake for Zotero 7 asap

**Comment by camillemndn** [comment]
Hi, you can use this now: https://github.com/camillemndn/zotero-nix
